spring:
  application:
    name: api-gateway
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://hongcd:123456@eureka-server:6571/eureka/, http://hongcd:123456@eureka-server:6572/eureka/
  instance:
    hostname: api-gateway
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
zuul:
  host:
    max-total-connections: 100
    max-per-route-connections: 20
  routes:
    striveConsumer:
      path: /feignConsumer/**
      serviceId: FEIGN_CONSUMER
    striveProvider:
      path: /provider/**
      serviceId: PROVIDER