spring:
  application:
    name: api-gateway
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://hongcd:123456@eureka-server:6571/eureka/, http://hongcd:123456@eureka-server:6572/eureka/
  instance:
    hostname: api-gateway
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
zuul:
  host:
    max-total-connections: 100 #\u6700\u5927\u8FDE\u63A5\u603B\u6570
    max-per-route-connections: 20 #\u5355\u4E2A\u8DEF\u7531\u6700\u5927\u8FDE\u63A5\u6570
  routes:
    striveConsumer:
      path: /feignConsumer/**
      serviceId: FEIGN_CONSUMER
    striveProvider:
      path: /provider/**
      serviceId: PROVIDER