spring:
  application:
    name: provider
eureka:
  instance:
    hostname: provider
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka-server:6571/eureka/, http://eureka-server:6572/eureka/